Jenkinsfile
electron-app/electron-builder.yml
electron-app/scripts/after-pack.js
theia-example-updater/package.json
theia-example-updater/src/electron-browser/theia-updater-frontend-module.ts
theia-example-updater/src/electron-browser/updater/theia-updater-frontend-contribution.ts
theia-example-updater/src/electron-browser/updater/theia-updater-preferences.ts
theia-example-updater/src/electron-main/update/theia-updater-impl.ts

This PR resolves #13
Besides deploying to version and platform specfic directories (e.g. https://download.eclipse.org/theia/1.9.0/linux/) we will also deploy to https://download.eclipse.org/theia/latest
The latest location will be used to fetch the latest updates. 
The application will check for updates after each launch. Checking for updates may also be triggered from the application menu. 
When an update is available, the user will be notified and may start the upgrade. 
Users may disable the notification for the automatic update check after program launch via preferences. 
* application will check for updates after the application is launched
* if update available prompt the user
* add preference to disable to check on startup
* use https://download.eclipse.org/theia/latest/ as …

Enable Updates for installed instances #13

---

electron-app/electron-builder.yml

Enables the user to select installation type on Windows for all users or only for current user:
* All users
* Current user 
No need to have administrator access to proceed with
installation for current user.
Contributed by STMicroelectronics
Run the installer on a windows machine, use an account without admin privileges and check that you are able to run Theia

Make it possible to install in user context (without administrator privileges)

---

electron-app/package.json

Fixes #48
ATM @theia/electron is a runtime dependency, that depends on the
"electron" package. As such both are preserved with the packaged
blueprint application.
Simple solution: make @theia/electron a dev-dependency, This way
it will be stripped when we package blueprint, somewhat reducing
our various package sizes. On Linux the expected size reduction
is 16MB.
Please see "steps to reproduce" in #48 and confirm that after the fix only a single version of Electron binaries are present in the unzipped package. 
Confirm that the app still generally starts and seems to works despite the absence of the package.

Make @theia/electron a development dependency

---

Dockerfile

Uses stretch instead of buster for building theia-blueprint for Linux. 
See #41 
Deploy a new version of thegecko/theia-dev with the modifed Dockerfile
Run a build on Jenkins
Verify that the AppImage is still working and that it is working on Ubuntu 18.04 now

Use older debian version for build #41

---

electron-app/package.json

Signed-off-by: Marc Dumais <marc.dumais@ericsson.com>
Fixes #52 by effectively reverting #49. I think I successfully tested that, but I can't make it work anymore, and the packages we generate are broken. It could be we actually need @theia/electron at runtime. Then we can instead try changing its electron dependency to a devDependency, which would remove the duplication of Electron binaries in our packages. 
Build and test the resulting app. E.g.:
```bash
$> yarn && yarn package
$> electron-app/dist/TheiaBlueprint-1.11.0.AppImage
```

Reverting @theia/electron as dev-dependency

---

Jenkinsfile

Update to use the new docker hub repo:
https://hub.docker.com/repository/docker/eclipsetheia/theia-blueprint

Switch to using eclipsetheia/theia-blueprint

---

theia-blueprint-product/src/browser/theia-blueprint-about-dialog.tsx
theia-blueprint-product/src/browser/theia-blueprint-getting-started-widget.tsx

Cleanup of a few more stray uses of the word 'product' in the application name
Signed-off-by: Brian King <brian.king@eclipse-foundation.org>
After starting up the latest alpha built, I noticed 'product' still in the title of the welcome page, so I changed it and a couple more instances I found.
In build with fix, open Welcome Page, About Dialog. Also check README in repo.
- [ ✅] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

Cleanup of a few more stray uses of the word 'product'

---

.vscode/theia.code-snippets
theia-blueprint-product/package.json
theia-blueprint-product/src/node/theia-blueprint-backend-module.ts
theia-blueprint-product/src/node/theia-blueprint-variables-server.ts

Related: https://github.com/eclipse-theia/theia-blueprint/issues/25#issuecomment-811871499.
The pull-request adds the following functionality:
- adds a custom configuration folder name (`.theia` > `.theia-blueprint`) to be used instead of the default.
- adds header snippets (from the upstream repository) to make it easier to add headers in the future.
- build and start the application.
- confirm that the `~/.theia-blueprint` folder exists on the filesystem.
- set user scope preferences, install extensions, and ensure they are saved under `~/.theia-blueprint`.

config: add custom home configuration folder

---

Jenkinsfile
applications/electron/electron-builder.yml

* switch mac target from pkg to dmg, because this allows auto-update
* see https://www.electron.build/auto-update
The .dmg should behave like the former .pkg however updates should work.  

Check for Updates gives no feedback if there is none [macOS] #71

---

Jenkinsfile

This reverts commit ad5a73c519d79d740e808296c1520962749ad167.
That committ was an attempt at improving the Jenkins CI reliability, but it has caused issues:
- the command is not OS-agnostic and does not work on at least Windows
- the /.cache folder, despite it's label, contains more than yarn, so removing it altogether is not a good idea. In any case `yarn cache clean` works perfectly, AFAICT. The attempted fix was more to address the 'electron-gyp` folder.
I might come-back with a follow-up, if I can successfully improve CI

Revert "Delete content of Jenkins job cache folders"

---

applications/electron/package.json

The affected section of the path is taken from the electron-app's author name. 
-> Change to "Eclipse Theia"
closes #35 
Build the windows installer and check the installation path for all users. 

Theia electron installer on windows has a hard coded default path #35

---

theia-extensions/theia-blueprint-product/package.json
theia-extensions/theia-blueprint-product/src/browser/theia-blueprint-about-dialog.tsx
theia-extensions/theia-blueprint-product/src/browser/theia-blueprint-getting-started-widget.tsx

Shows vscode extension API version in About dialog
closes #86
Build and check about dialog

Show vscode extension API version in About dialog #86

---

theia-extensions/theia-blueprint-product/src/browser/theia-blueprint-getting-started-contribution.ts

* avoid contributing the menu contributions twice
closes #110 
Build and check that the help menu has only one "Getting Started" entry and that the welcome page is still shown on every launch even when a workspace is already opened.

Getting started shown twice in help menu #110

---

Jenkinsfile

* Only stash directory containing linux installer for linux
closes #120 
Check CI

[Jenkins] "OutOfMemoryError: Java heap space" during stash

---

.github/workflows/publish-builder-img.yml
Dockerfile

This PR adds a GH workflow that builds  our Blueprint builder image and publishes it to Docker Hub. The workflow should be able to be triggered from the `Actions` tab on our GH project and as a fallback it's scheduled to run the 1st of every month. 
As a troubleshooting step, I first had the image build on any push, and so the current `Dockerfile` has [already been published](https://github.com/eclipse-theia/theia-blueprint/runs/3145434270?check_suite_focus=true).

[ci] add workflow to rebuild and publish builder image

---

theia-extensions/theia-blueprint-product/package.json
yarn.lock

The commit addresses issues where building the project caused `yarn.lock` updates, and would pull different versions of the framework.
1. confirm that `yarn` does not cause git changes
2. confirm that `yarn start:electron` works

Fix incorrect `@theia` dependency version ranges

---

.github/workflows/build.yml

The commit includes a `github actions` workflow for the project (in addition to the already existing jenkins build). The workflow will
hopefully help contributors identify issues in prs and cron job sooner.
The CI should pass:
- build
- lint

ci: add `github actions` workflow

---

theia-extensions/theia-blueprint-product/src/browser/theia-blueprint-about-dialog.tsx
theia-extensions/theia-blueprint-product/src/browser/theia-blueprint-getting-started-widget.tsx

The commit updates the vscode api version for the `about` and `getting-started` views to use a non-deprecated way to determine the currently supported API version following recent changes to the framework.
1. perform `yarn`
2. start the electron app - `(cd applications/electron && yarn start)`
3. confirm that the `about` dialog displays correctly, and has the proper api version
4. confirm that the `getting-started` page displays correctly and has the proper api version

Update `about` and `getting-started` api-version handling

---

applications/electron/package.json

fixed #123
Signed-off-by: Jonas Helming <jhelming@eclipsesource.com>
Removes the Eclipse key bindings
Press CTRL+D, it should not delete a line

Removed Eclipse key bindings

---

.gitignore
README.md
applications/electron/webpack.config.js

Checks the user configurable `webpack.congig.js` into the git.
close #134
- see [e2e-est](https://github.com/eclipse-theia/theia-blueprint/blob/master/README.md#running-e2e-tests) 
- make sure that file is not ignored

Fix webpack config

---

applications/electron/electron-builder.yml
applications/electron/package.json
theia-extensions/theia-blueprint-product/src/browser/theia-blueprint-frontend-module.ts
theia-extensions/theia-blueprint-product/src/browser/theia-blueprint-getting-started-contribution.ts
theia-extensions/theia-blueprint-product/src/node/theia-blueprint-backend-module.ts
theia-extensions/theia-blueprint-product/src/node/theia-blueprint-variables-server.ts
theia-extensions/theia-blueprint-updater/package.json
theia-extensions/theia-blueprint-updater/src/electron-browser/theia-updater-frontend-module.ts
theia-extensions/theia-blueprint-updater/src/electron-browser/updater/theia-updater-frontend-contribution.ts
theia-extensions/theia-blueprint-updater/src/electron-main/update/theia-updater-impl.ts
theia-extensions/theia-blueprint-updater/src/electron-main/update/theia-updater-main-module.ts
yarn.lock

Fixes: https://github.com/eclipse-theia/theia-blueprint/issues/48.
The commit includes the following updates:
- removes nested `electron` from the packaged application.
- removes unnecessary `electron` dependencies
- updates `electron` and `inversify` to use `@theia/core/shared` dependencies
- confirm that `yarn` works
- confirm that `yarn package` works for the `applications/electron`
- confirm that the packaged application starts correctly
- confirm that there is no nested `electron` binaries:
```
$ find . -name libvulkan.so
./dist/linux-unpacked/libvulkan.so
```

electron: fix electron issues

---

applications/electron/test/app.spec.js

Fixes: #123
The pull-request removes the leftover assertion in the test-case to verify that `eclipse keymaps` is in fact present as a built-in extension. Since #140 the extension was removed but the test-case was no updated leading to the test suite failing.
1. `yarn`
2. `(cd applications/electron && yarn package:preview)`
3. `(cd applications/electron && yarn test)`

test: remove 'eclipse keymaps' from test

---

applications/electron/scripts/after-pack.js

This is a follow-up on the recent commit that made signing
on Mac happen only when running Jenkins CI. The printout
above was added for all operating systems, but it really
only makes sense to have it when one is running on a Mac.
This commit removes the printout on other platforms.

Remove "Skip Mac CI signing" printout if not on Mac

---

.github/workflows/build.yml
Jenkinsfile

See this [related proposal (#148)](https://github.com/eclipse-theia/theia-blueprint/issues/148)
What this PR does:
- enhance our GH workflow to generate Blueprint packages for our supported operating systems and run our test suite on them.
- only run Jenkins CI when merging on master or when we have reasonable suspicion(1) that the PR is related to Jenkins configuration changes. This will let us detect Jenkins update issues without having to merge to master first.
-  technically the CI step still runs, but it will successfully exit almost immediately for most PRs. The `when` condition is used in `Jenkinsfile` to inhibit running the `Build` and `Sign and Upload` pipelines stages.
This will save a lot of CI time and insure Jenkins executor are available when we really need them: when we …

[CI] Streamline project's CI

---

Jenkinsfile

This is a follow-up to #143. After merging, I noticed that
Jenkins CI run was unexpectedly streamlined:
https://ci.eclipse.org/theia/job/Theia2/job/master/5/console
Looking at that log, it seems the environment available from
Jenkinsfile is a bit different, when merging vs when it's a PR.
Variable "env.CHANGE_BRANCH" is not set when merging,
so the "when" conditions did not work as expected.
Looking at a recent log for master, it seems "env.GIT_BRANCH"
is set and has correct value, so let's try using that instead.
log: https://ci.eclipse.org/theia/job/Theia2/job/master/4/consoleFull
Make sure CI passes as expected. For the "merging to master" part, other than double-checking the change, I think we will need to merge to confirm that this works.
- as a reviewer, I agree to behave in …

[CI] follow-up: fix Jenkins CI when merging

---

Jenkinsfile
applications/electron/electron-builder.yml
applications/electron/package.json
applications/electron/scripts/update-checksum.ts
yarn.lock

This PR addresses the updates on windows and mac.
For Windows the issue is that the eclipse code signing changes the checksum. During build the checksum is computed before the code signign and saved in the latest.yaml (https://download.eclipse.org/theia/latest/windows/latest.yml) which is used for the update process. This checksum needs to take the signing process into account. 
Furthermore the electron-updater has an issue with non-unique file-names for the installer. We are using TheiaBlueprint.exe as the file-name (to have stable download links without the need to update the download page on every release). During the update process this leads to the point that Theia Blueprint is uninstalled but then the new version is not installed. This can be addressed by including the version in …

Auto-Updater may fail for signed electron apps #116

---

applications/electron/package.json
yarn.lock

This PR removes most of the vscode built-ins, that were previously listed individually, and replaces them with the [built-in extensions pack](https://open-vsx.org/extension/eclipse-theia/builtin-extension-pack/1.50.1), that we recently produced. That pack contains all built-ins, so Blueprint will now provide, OOTB, provide very similar feature as VS Code, including grammars that enable syntax highlight in many languages and e.g. themes.
There is one extension ATM that does not work as expected from the pack, that we pin to a specific version known to work better: `vscode.git`, and one extension that we exclude: `vscode.extension-editing`.
__update:__ we added a second one, `vscode.markdown-language-features`, that we now pin to an earlier version, that's known to work well.
Also included …

Replace vscode built-ins by extension pack

---

applications/electron/package.json

The commit adds `vscode.microsoft-authentication` in the list of builtins to exclude from the bundled application since it is not
required or wanted by default. The extension is used to perform preference syncing to microsoft services.
Confirm that the `vscode-microsoft-authentication` plugin is skipped and not included in the final application.

builtin: exclude `microsoft-authentication`

---

lerna.json
package.json
yarn.lock

Fixes: #174 
The pull-request bumps the version of `lerna` for the project since the older version of lerna had a few high level vulnerabilities.
The new `yarn audit --level=high` output is the following:
```
$ yarn audit --level=high
yarn audit v1.22.4
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Regular Expression Denial of Service (ReDoS)                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ is-svg                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.2.2                                                      │ …
```

deps: bump `lerna` version

---

Jenkinsfile
applications/electron/electron-builder.yml
applications/electron/scripts/after-pack.js
applications/electron/scripts/notarize.sh
applications/electron/scripts/sign.sh

We use `build.eclipse.org` in our JenkinsFile and elsewhere. Let's try updating it to the suggested replacement server and hope this does the trick.
We also used a non-standard server for notarization: updated too.
more about the server decommission: 
https://wiki.eclipse.org/IT_Infrastructure_Doc#Web_service
https://www.eclipse.org/lists/eclipse.org-committers/msg01318.html
https://blogs.eclipse.org/post/denis-roy/bye-bye-build-end-era
https://bugs.eclipse.org/bugs/show_bug.cgi?id=565644
Also update URL of MacOS notarization service, in the few places
where we use the service, as per the documented example:
https://wiki.eclipse.org/IT_Infrastructure_Doc#macOS_Notarization
Use fail-fast option of curl, since this permits to immediately
detect if there's an issue with the macOS signing …

[CI] Replace decommissioned build.eclipse.org server in Jenkins config

---

theia-extensions/theia-blueprint-updater/src/common/updater/theia-updater.ts
theia-extensions/theia-blueprint-updater/src/electron-browser/updater/theia-updater-frontend-contribution.ts
theia-extensions/theia-blueprint-updater/src/electron-main/update/theia-updater-impl.ts

Add an action to the error notification that allows the user to see the log file with the full error message.
The path to the error log is retrieved from the logger that was used to record the error. The path must be given as part of the error object for the action button to appear.
Fixes #161 
Start electron app `yarn electron start` and check for updates from Main Menu Bar -> File -> Settings -> Check for updates..
An error notification should show, with a message and a `View Error Log` button that opens the error log when clicked.

[Updater] Allow to inspect logs on error

---

next/Jenkinsfile

In `next/Jenkinsfile`, we set environment variable `BLUEPRINT_JENKINS_CI`. It's then used in the `electron-builder` post-packaging [script](https://github.com/eclipse-theia/theia-blueprint/blob/master/applications/electron/scripts/after-pack.js#L43) as part of a [test](https://github.com/eclipse-theia/theia-blueprint/blob/master/applications/electron/scripts/after-pack.js#L55) to determine if we should proceed with signing and notarization. 
I believe it should not for `next` CI, since we do not publish the resulting packages. So we probably do not want `BLUEPRINT_JENKINS_CI` set.
Signed-off-by: Marc Dumais <marc.dumais@ericsson.com>
I think we will need to merge to properly test this change. The CI this PR will go through will still set the environment variable, and so will not be …

[Jenkins] [next] [mac] disable signing

---

package.json
yarn.lock

The recent update of `eslint-plugin-deprecation` pulls in a newer version of `@typescript-eslint/experimental-utils`.
This version is not compatible with the node versions available on the shared windows and mac build nodes. 
(For Linux we could update the docker image):
`error @typescript-eslint/experimental-utils@5.8.0: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.17.0 || >=16.0.0". Got "12.20.0"`
https://ci.eclipse.org/theia/job/Theia2/job/master/16/consoleText
For now set a resolution for `eslint-plugin-deprecation` to the version known to work.
Build with a node version lower than 12.22 and check whether the build succeeds
- as a reviewer, I agree to behave in accordance with [the review …

Set resolution for eslint-plugin-deprecation plugin

---

applications/electron/package.json
package.json
yarn.lock

* Fix yargs version to 17.2.1. Higher versions can't compile `update-checksum.ts` anymore.
* This is the script that is used to update the checksum on the windows machine after the installer was signed by eclipse
* This should fix the current master build for Windows as well, so that the Theia 1.21 update is available with Blueprint: https://ci.eclipse.org/theia/job/Theia2/job/master/
* Build blueprint `yarn && yarn electron package`
* Check if the checksum update script can be executed again (adjust args based on your OS)
`yarn electron update:checksum -e TheiaBlueprint.exe -y latest.yml`

Fix yargs version to 17.2.1

---

theia-extensions/theia-blueprint-product/src/browser/style/index.css
theia-extensions/theia-blueprint-product/src/browser/theia-blueprint-frontend-module.ts
theia-extensions/theia-blueprint-product/src/browser/theia-blueprint-getting-started-contribution.ts
theia-extensions/theia-blueprint-product/src/browser/theia-blueprint-getting-started-widget.tsx
theia-extensions/theia-blueprint-product/src/browser/theia-blueprint-preferences.ts

* adds preference whether to always show the welcome page
* check preference from getting started contribution
* add checkbox on welcome screen and sync with preference
Fixes #185
Build and test the setting from preferences and from welcome page.
Test that settings are synced between welcome page and preferences. 
Please note that when the checkbox get unchecked and the welcome page was not closed, it will get restored just like any other view. So in order to test this, the welcome page needs to be closed between reloads. 

Have a way to not show Blueprint welcome screen

---

next/Jenkinsfile

Recently we had build issues (on the Eclipse CI) after running `yarn upgrade`. 
This PR also runs `yarn upgrade` during our nightly `next` build. This should help to identify version ranges that are too broad earlier. 
I think it needs to be executed on the CI for testing. 
I've did some testing here: https://ci.eclipse.org/theia/job/theia-next/job/jf%252Fnext/

Run yarn upgrade during next build

---

theia-extensions/theia-blueprint-product/src/browser/theia-blueprint-getting-started-contribution.ts
theia-extensions/theia-blueprint-product/src/browser/theia-blueprint-getting-started-widget.tsx

* open getting start view with activate request
* set focus to always show welcome page checkbox when activated
Fixes #198
Build blueprint and check whether the welcome page tab is shown as active when focused (see STR in https://github.com/eclipse-theia/theia-blueprint/issues/198)

Welcome page tab not marked as active when focused #198

---

Dockerfile

Install the required python version in the stretch docker image used for
building for linux manually. Since we want to support Ubuntu 18.04 we
should still build with stretch.
Fixes #208 (python part)
It possible to test via building the docker image locally (may take some time)
`docker build -t my-blueprint-builder .`
and then run the blueprint build locally with this image:
```
docker run --rm -ti \
--env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS_TAG|TRAVIS|TRAVIS_REPO_|TRAVIS_BUILD_|TRAVIS_BRANCH|TRAVIS_PULL_REQUEST_|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_') \
--env ELECTRON_CACHE="/root/.cache/electron" \
--env ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder" \
-v ${PWD}:/project \
-v ${PWD##*/}-node-modules:/project/node_modules \ …
```

Eclipse CI build issues (Python version) #208

---

applications/electron/package.json
package.json

Align used engines with Theia Main Repository
* do not force node 12 (will be EOL soon)
* adapt yarn constraint
Theia Links:
https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#prerequisites
https://github.com/eclipse-theia/theia/blob/6d67d664bd3f679fca68be51d06d360a115decb2/package.json#L5
Building should still work. I've tested locally with node 12 and 14.

Align used engines with Theia

---

theia-extensions/theia-blueprint-updater/src/electron-browser/updater/theia-updater-frontend-contribution.ts

Previously, the update dialogs gave the impression that a downloaded update wouldn't get installed if answering 'No' in the second dialog. Since this isn't the case, make it clear in the message that the update will get installed on application exit and that the question is whether to restart now or not.
Below screenshots show the new texts:
Fixes #212
Contributed by STMicroelectronics
Signed-off-by: Erik LUNDIN <erik.lundin@st.com>
The old messages can easily be seen with a version of Theia Blueprint that isn't the latest (otherwise no update dialogs will show). To see the new messages, the application has to be tricked that there is a new update available. I found out how to create a fake `app-update.yml` and set up a simple HTTP server to serve the update metadata and a fake appimage …

Clarify update dialogs

---

next/Jenkinsfile
package.json

Currently the next build on Jenkins fails after running `yarn upgrade`. 
This commit sets a resolution for `electron-store` to the currently used version. 
Once we do our next dependency upgrade we should investigate this in more detail. 
Besides that change this commit adds a sleep between retries. 
What we see often for the Linux build on Jenkins are failures when npm packages download content from github. 
This is probably due to rate-limits: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/912
Without the sleep the following builds will fail as well, since the limiting is still in place. I would like to see whether this will improve the situation for the next build. If so, I will make this change to the actual build as well. 
Regular build should still work. 
`yarn && yarn …

Fix electron store version, Add sleep between retries

---

Dockerfile

Updates our docker image for building on the eclipse ci to node 14, because this is the new Theia lower bound: https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#prerequisites
Build the image locally and check whether building the image works. 

Update Build Dockerfile to Node 14

---

Jenkinsfile
next/Jenkinsfile

Windows and Mac Agents have been updated to use node 14.20.0
After the update we ran into the following issue on the windows agent:
https://github.com/nodejs/node-gyp/issues/2584#issuecomment-1064727363
This PR implements the workaround from the ticket
Check Jenkins Build result: https://ci.eclipse.org/theia/job/Theia%20PRs/job/PR-225/

Preinstall node-gyp on windows CI ( Jenkins )

---

.gitpod.dockerfile
.gitpod.yml

I find Gitpod is useful for quickly testing some PRs. ATM the node version
used is not compatible with Theia and so the build fails. This commit updates
the config to use node 14.
Also start the electron version of Blueprint when the build is done. It's
accessible from the Ports view (bottom bar) by selecting "open browser" 
in line "port 6080".
In the PR's CI steps, click on the "Details" link next to the `Gitpod` check. Confirm that the Blueprint build is successful in the Gitpod terminal.

[Gitpod] update config to use node 14

---

package.json
yarn.lock

Update theia-blueprint to remove security vulnerabilities in the dependencies, mainly by upgrading our version of lerna + yarn upgrade
In Command prompt, navigate to the Theia-blueprint file and run the following command line:
yarn cache clean && git clean -ffdx && yarn && yarn electron start

Theia Blueprint update - Lerna updated version & yarn upgrade

---

theia-extensions/theia-blueprint-launcher/package.json
theia-extensions/theia-blueprint-launcher/src/node/launcher-endpoint.ts

When starting the application from a terminal, using the installed `theia` command, keep the terminal clean and log all output to a log file. For now, the contents of the log file are overwritten on each application restart.
- Start the application from the AppImage and in the dialog that prompts you to create the launcher, select Yes.
- Open a terminal and type `theia`.
- The application should launch and no logs should be shown in the terminal from which it was started.
- The logs can be found in `~/.theia-blueprint/logs/launcher.log`
- Replace the old AppImage with the new version containing the code from this PR. The path to the old file can be found in `~/theia-blueprint/globalStorage/blueprint-launcher/paths.json`. Alternatively, you can delete the paths.json file and open the …

launcher: remove logs from terminal when launching app

---

.github/workflows/publish-blueprint-img.yml
README.md
applications/browser/package.json
applications/browser/resources/preload.html
applications/browser/tsconfig.json
applications/browser/webpack.config.js
applications/electron/package.json
browser.Dockerfile
package.json
theia-extensions/theia-blueprint-product/package.json

* create a dedicated browser application
* adapt product so that frontend code is useable from browser app as well
* move electron:rebuild to laters stage to avoid conflicts between both applications
* Create Dockerfile with Github Workflow and adapt Readme
* Check whether electron based app is still working
* Test browser application with `yarn browser start`
* Test Dockerfile and image with instructions from Readme

Create Browser Application and Dockerfile #75

---

.github/workflows/publish-blueprint-img.yml
.github/workflows/publish-builder-img.yml
Jenkinsfile
applications/browser/package.json
browser.Dockerfile
next/Jenkinsfile

* remove unnecessary packages from blueprint docker image
* publish to github container registry as well (see comment on #253)
* comment out dockerhub until repository is available
* adapt tags of builder image to be less confusing (see comment on #253)
* set warnOnPotentiallyInsecureHostPattern to false, so that adopters may override the host patterns. We keep the defaults, that don't trigger a warning. 
* add comments to browser.Dockerfile so that adopters may adjust this more easily
I've tested the publish step and the package is available here: https://github.com/eclipse-theia/theia-blueprint/pkgs/container/theia-blueprint%2Fblueprint
```
docker run -p=3000:3000 --rm ghcr.io/eclipse-theia/theia-blueprint/blueprint:1.35.0
```
New Builder image was created with this run: …

Docker improvements (Jenkins)

---

Dockerfile

* also use python from package repository again
One way would be to build the image locally, start the container, and clone theia-blueprint in the container and build the next branch. This is currently failing on the CI. 
```
docker build -t eclipsetheia/theia-blueprint:local .
docker run --rm -it --entrypoint /bin/bash eclipsetheia/theia-blueprint:local
cd /tmp
git clone https://github.com/eclipse-theia/theia-blueprint.git
cd theia-blueprint
git checkout -b next origin/next
yarn
yarn upgrade
yarn
yarn electron package:preview
```

Update Jenkins Builder Image to Node 16

---

.vscode/launch.json

Update browser related launch config to use the correct application path.
Removes the apparently no longer used config for running playwright tests.
The `Launch Browser Backend`, `Launch Browser Backend (eclipse.jdt.ls)` and `Launch Electron Backend & Frontend`  configs should no longer fail and correctly startup the browser application.

Fix browser launch configs

---

cleanup/Jenkinsfile

Adds a build job that cleans up the windows temp directory (including some logs to see what is happening) regularly. 
We could either trigger the Job timer-based (e.g. once a week) or run it after certain build jobs. 
Can only be tested on Eclipse CI. 
I've set up a Job that currently runs from the branch atm: https://ci.eclipse.org/theia/job/Theia%20-%20Cleanup%20Build%20Nodes/job/jf%252Ftemp-cleanup/11/console
The Job is currently configured to run once a week. 

[CI] [Jenkins] Clean-up tmp files on Windows agent after CI run

---

cleanup/Jenkinsfile

Looking at the [log of the first run](https://ci.eclipse.org/theia/job/Theia%20-%20Cleanup%20Build%20Nodes/job/master/1/consoleFull), I noticed that seemingly no `yarn--<random number>` or `theia-plugin-download<random identifier>` file were found or cleaned. It was confirmed in the Gitlab ticket that these two types of files are still present on the server.
In this PR, I adapt the pattern we use for those two file types.  I also handle the case of the "theia-plugin-download**" files differently, looking-for and deleting individual files that match the pattern rather than directories.
Finally I made misc little tweaks based in linter feedback.
I think we will need to merge the PR in order for it to run on Jenkins?
- as a reviewer, I agree to behave in accordance with [the review …

A few tweaks to the new "cleanup" Jenkins file

---

theia-extensions/theia-blueprint-updater/src/electron-browser/updater/theia-updater-frontend-contribution.ts

Fixes #273 by removing imports from node. The required functions are available on `Window` as well.
https://developer.mozilla.org/en-US/docs/Web/API/setInterval
https://developer.mozilla.org/en-US/docs/Web/API/clearInterval
1. First increase version in `applications/electron/package.json` to e.g. `1.39.1`
2. `yarn && yarn electron package`
3. Copy `applications/electron/dist` directory to some other location
4. Run `npx serve -d -u -p 5000` in the copied dist directory to serve this build as a potential update
5. Undo the change from step 1
6. Update the `url`s in `applications/electron/electron-builder.yml` to `http://localhost:5000`
7. Run `yarn && yarn electron package` …

Remove timers import from node and use from Window instead #273

---

applications/electron/scripts/after-pack.js

I noticed an issue after merging PR #272, looking at the [Jenkins build log](https://ci.eclipse.org/theia/job/Theia2/job/master/116/console). 
To save build time, we only proceed with macos signing/notarising when it's detected that the current build is producing official blueprint packages. Unfortunately a little bug was introduced in https://github.com/eclipse-theia/theia-blueprint/pull/272 , that prevents this mechanism from working, resulting in an unsigned/un-notarised macos package \[1\]. 
This is the fix.
\[1\]: note: I killed the Jenkins build before if got far enough to potentially release a bad macos package.
Unfortunately I think we need to merge to be certain. But I think the fix is simple enough to be validated by looking at the Jenkins linked log above.
- as a reviewer, I …

Follow-up: fix detection of production mac build

---

browser.Dockerfile

Fixes wrong paths and removes an unnecessary option.
Rebuilding the Docker image
I don't know what *thoroughly* means however I could successfully build the Docker image.
---
closes  #309

`browser.Dockerfile`: Fix `rm` command

---

applications/electron/package.json
yarn.lock

The electron-chromedriver matches the electron version we are using. Mac Silicon (darwin-arm64) has only been supported since v11.0.0 and v9.0.0 build will fail.
Fixes https://github.com/eclipse-theia/theia-blueprint/issues/308
- Build on Mac Silicon.

Ensure we use the correct electron-chromedriver version

---

Jenkinsfile
releng/promote/Jenkinsfile
theia-extensions/updater/src/common/updater/theia-updater.ts
theia-extensions/updater/src/electron-browser/updater/theia-updater-frontend-contribution.ts
theia-extensions/updater/src/electron-browser/updater/theia-updater-preferences.ts
theia-extensions/updater/src/electron-main/update/theia-updater-impl.ts

The goal of this PR is to add a second update channel. 
Until now every commit was built and the result was pushed to https://download.eclipse.org/theia/ide/
With this PR we will instead push the results to https://download.eclipse.org/theia/ide-preview/
The ide-preview location may be used for testing the IDE before we promote it to https://download.eclipse.org/theia/ide/
For the promotion there will be a new Jenkinsfile in this PR that will be used to copy the results. 
This needs to be triggered manually on the build server then. 
Finally there is a new preference for selecting an update channel. 
The current options are `stable` (https://download.eclipse.org/theia/ide/ Released Theia Version, Theia IDE was tested before promotion) and `preview` …

Introduce Update Channels #278

---

applications/electron/package.json
applications/electron/scripts/after-pack.js
yarn.lock

This is the fix of https://github.com/eclipse-theia/theia-blueprint/pull/340 (which got closed accidentally) including a required fix (`electron-osx-sign` is not bundled with `app-builder-lib` anymore). 
Build blueprint and check if still working. 
Verify CI Builds on this PR.

Dependabot/npm and yarn/app builder lib 24.13.2

---

browser.Dockerfile

Resolves https://github.com/eclipse-theia/theia-blueprint/issues/345
`node:16-bullseye` seems outdated and resulted in the bug documented in the above issue.  It is not currently supported on the official list of node docker images: https://hub.docker.com/_/node
The issue at https://github.com/eclipse-theia/theia-blueprint/issues/345 was resolved even by changing to `node:18-bullseye` only in the `build-stage`, but presumably it should be already upgraded also in the `production-stage`, so this commit/PR also updates the production stage based image.
Following/repeating the instructions here: https://github.com/eclipse-theia/theia-blueprint/issues/345
1. `git clone https://github.com/eclipse-theia/theia-blueprint`
2. `cd theia-blueprint`
3. `docker build -t theia-ide -f browser.Dockerfile …

Updated docker base image to node:18-bullseye in browser.Dockerfile

---

Jenkinsfile
applications/browser/package.json
applications/electron/package.json
lerna.json
package.json
theia-extensions/launcher/package.json
theia-extensions/product/package.json
theia-extensions/product/src/electron-main/icon-contribution.ts
theia-extensions/updater/package.json
yarn.lock

Removes remaining usage of `app-builder-lib@23.6.0` that was not updated by the dependabot PR
Upgrades all dependencies
Fixes  #361 AppImage does not show a launcher Icon anymore
Build application on Linux and check that icon is showing. 

AppImage does not show a launcher Icon anymore + Remove all usages of app-builder-lib@23.6.0 + yarn upgrade

---

applications/electron/webpack.config.js

Update webpack config to not run TerserPlugin in parallel. 
Running in parallel may lead to OOM issues on smaller/shared build nodes
The Job that ran out of memory during webpack: https://ci.eclipse.org/theia/job/Theia2/job/master/158/
We had similar issues here: https://github.com/eclipse-cdt-cloud/cdt-cloud-blueprint/pull/91
Check if build still works

Do not run TerserPlugin in parallel

---

applications/electron/electron-builder.yml

This allows right-click open folder with Theia IDE by default on KDE.

Add Linux MIME types

---

browser.Dockerfile

When building this dockerfile I get warnings with docker
```
WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 2)
WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 29)
```
```
docker build -t theia -f browser.Dockerfile .
```

Fix dockerfile warnings in browser.Dockerfile

---

Jenkinsfile
PUBLISHING.md

* compute versions to update when publishing preview
* update publishing documentation
We have to test on next release. 
However I did a test run with an adjusted Jenkinsfile and this was the result printed:
https://ci.eclipse.org/theia/job/Theia%20PRs/view/change-requests/job/PR-411/4/execution/node/173/log/
Which shows all contents of https://download.eclipse.org/theia/ide-preview/ but latest (not a version number) and 1.54.0 (same version as current version)

Improve Release Flows

---

package.json

This adds the builtin extensions for notebook support by default to the plugins folder.
Currently this is kind of confusing for most users coming from vscode, that they have to install 2 additional extensions they might never have heard about (the butilin ipynb and builtin notebook renderers). Having the support available by default should make this far easier. 

add notebook-support by default

---

applications/electron/scripts/after-pack.js

Without this the AppImage is not running properly on newer Ubuntu versions. For more information see #363.
1. Package the electron application (`yarn && yarn build && yarn download:plugins && yarn electron package`)
2. Start the AppImage and notice that it is running with the `--no-sandbox` option
3. Start the .deb and notice that the `--no-sandbox` option is not present

Start AppImage with --no-sandbox option

---

applications/browser/webpack.config.js
applications/electron/webpack.config.js

scanoss depends on `node-fetch` <`3`. node-fetch in that version fails their instance checks, as it relies on constructor/class names which are removed by the backend bundling.
Customizes the webpack configurations to keep the class name for 'AbortSignal' as this is the one failing the check.
Build the Browser and/or Electron **production** builds and make sure that SCANOSS keeps working.

fix: scanoss bundling

---

applications/browser/package.json
applications/electron/package.json

The rebuild cache of Browser and Electron needs to point to the same directory, as otherwise they do not work properly: The Browser rebuild just restores the cached modules which is not possible if they do not point to the same directory.
Build the Browser app after the Electron app has been built. As the cache directory is not the same, the Browser modules will not be restored from the cache. Therefore the Browser build will use the Electron modules at build time and then crash at startup.
```
yarn && yarn electron build && yarn browser build && yarn browser start
```

dev: fix rebuild

---

Jenkinsfile
applications/browser/package.json
applications/electron/package.json
lerna.json
package.json
theia-extensions/launcher/package.json
theia-extensions/product/package.json
theia-extensions/updater/package.json

We are investigating update issues on macOS, which might be related to signing. As part of this effort, we are also testing the new Eclipse signing service.
This version might not be promoted from preview to the stable channel immediately but instead with the next Theia release.
* ~~test new signing service as standin~~ (gave an error, will investigate later)
* also sign and notarize zip file itself on mac
* bump timeout to 5 hours, since Eclipse CI is sometimes just slow
Mac DMG should still work and updating should not lead to a loop (we will have to merge this to get testers in)

Mac Updater Issues

---

Jenkinsfile
applications/browser/package.json
applications/electron/package.json
applications/electron/scripts/update-blockmap.ts
applications/electron/scripts/update-checksum.ts
lerna.json
package.json
theia-extensions/launcher/package.json
theia-extensions/product/package.json
theia-extensions/updater/package.json

Based on the learnings from https://github.com/eclipse-theia/theia-ide/pull/439 we will now fix the checksums for the mac build as a first step. 
* also extend update checksum script to have more control over what happens (when to update paths, which files to update)
* bump versions to 1.57.102
Again this change is mainly for testing and will probably not get promoted before 1.58
Green Build with release dry run: https://ci.eclipse.org/theia/job/Theia%20PRs/view/change-requests/job/PR-440/4/
Check logs with output, maybe best place is here: 
https://ci.eclipse.org/theia/job/Theia%20PRs/view/change-requests/job/PR-440/4/flowGraphTable/
https://ci.eclipse.org/theia/job/Theia%20PRs/view/change-requests/job/PR-440/4/execution/node/249/log/ …

Update Checksums for Mac Build after Signing

---

applications/browser/package.json

Configures 'reloadOnReconnect' and 'frontendConnectionTimeout' in the browser application to improve the user experience.
Resolves https://github.com/eclipse-theia/theia/issues/14516
Run the Browser application and check the connection behavior after a few minutes. See https://github.com/eclipse-theia/theia/issues/14516 for the problematic behavior

fix: improve connection settings in browser application

---

applications/browser/package.json
applications/electron/package.json
lerna.json
package.json
scripts/make-files-writeable.ts
theia-extensions/launcher/package.json
theia-extensions/product/package.json
theia-extensions/updater/package.json

Follow up of https://github.com/eclipse-theia/theia-ide/pull/440
Checksums looked right and we were able to debug further. 
It looks like some files in the Java VSIX are not writable and the Mac Updater tries to change permissions there, leading to a failure. 
* make sure that plugin files are writable so that Mac may set/remove quarantine bits
* also bump patch versions
Again, this Preview will probably not be promoted, Changes will go live with 1.58

Make plugins writeable

---

Jenkinsfile
applications/browser/package.json
applications/electron/package.json
lerna.json
package.json
theia-extensions/launcher/package.json
theia-extensions/product/package.json
theia-extensions/updater/package.json

With our recent commits for Mac, we fixed that all file contents were replaced during and update. 
However, on newer Mac versions, the default unpacking process no longer preserves Unix file permissions, even though they are correctly set in the zip.
The current workaround is to use unzip on the CLI, which preserves file permissions, and then use ditto to recreate the zip on Mac.
Unfortunately, we have no control over the initial zip creation, as it is the result provided by Eclipse's signing and notarization services.
We will do a preview build that will not be promoted. 

Use Ditto to create Zips for Mac

---

Jenkinsfile
applications/browser/package.json
applications/electron/package.json
lerna.json
package.json
theia-extensions/launcher/package.json
theia-extensions/product/package.json
theia-extensions/updater/package.json

On some (not all) Mac machines, we encounter issues with the Zip itself (even when running it directly, not just after an update), while the Dmg works fine on all test machines.
-> Investigate if producing the Zip based on the signed and notarized Dmg yields better results. It’s possible that the Eclipse signing service handles the Zip differently than the Dmg.
Result:
-> Both the Dmg and Zip are stored in the PR verification job. Both started fine on all testing machines: https://ci.eclipse.org/theia/job/Theia%20PRs/view/change-requests/job/PR-450/
-> Let’s verify if updates still work.

Create Update Zip based on dmg

---

.vscode/launch.json

Adapts the browser launch configurations to use the bundled backend. This allows to start the browser application after it was built once, independent of the current state of the native Node module dependencies.
- Built the Browser application
- Build the Electron application
- Use the launch configuration to start the Browser application
- Observe that it now succeeds to start

dev: use bundled backend in launch configurations

---

theia-extensions/product/src/browser/style/index.css
theia-extensions/product/src/browser/theia-ide-getting-started-widget.tsx

This way we do not need to manually adapt the text in the AI Banner, when its updated in the framework.
Also added a padding to the float container as this looked odd before.
Upstream PR that improves the spacing in the AI Banner: https://github.com/eclipse-theia/theia/pull/15106
Screenshot on how this will look with the next release:

Sync getting-started-page with framework

---

releng/preview/Jenkinsfile.sign

Adds a few more retries to the signing job to be able to recover from failed executions
Remark: currently the Jenkins job runs using this branch, after merging, I will restore it again to run on master.
See the latest run of `Theia IDE - Sign & Notarize Preview` was using the retries: https://ci.eclipse.org/theia/job/theia-ide-sign-notarize/
E.g. in the following run the `Mac: Recreate Zip with Ditto for correct file permissions` stage was retried and was then successful: https://ci.eclipse.org/theia/job/theia-ide-sign-notarize/64/console

chore: update Jenkins file for signing
