eclipse-theia/theia-ide

electron-app/package.json
Remove markdown-language-features for now. 
Will be readded as part of #26
Build should work again
=> Remove markdown-language-features for now

theia-example-updater/src/electron-browser/customization/branding-util.tsx
Signed-off-by: Brian King <brian.king@eclipse-foundation.org>
A pass through the text and have some minor suggestions. The main one is not using the term 'Eclipse Theia Blueprint product' andf replacing it with just 'Eclipse Theia Blueprint'.
=> Issue #32: Content suggestions for about / welcome text

README.md
Signed-off-by: thegecko <rob.moran@arm.com>
=> Remove unused link to old travis CI project

Jenkinsfile
Signed-off-by: thegecko <rob.moran@arm.com>
Clear out latest folder prior to deploying. This ensures the latest folder only contains a single release.
cc @brianking @jfaltermeier @koegel
=> Clear latest folder prior to deploy

.gitignore, electron-app/scripts/notarize.sh, electron-app/scripts/sign.sh, theia-blueprint-product/package.json, theia-blueprint-updater/package.json, yarn.lock
* use scp command with "Disable strict filename checking."-flag
* also fix some smaller issues noticed during mac testing (gitignore, yarn lock)
Run Build in CI. Mac Build should work again
=> Fix Mac Build on CI

.gitpod.dockerfile, .gitpod.yml
ATM it's difficult to produce Blueprint installers for test purposes in a
reproducable way, e.g. to test PRs. Though not mandatory for
anyone to use, Gitpod is used by several committers and permits
programmatically generating a workspace that contains the
Linux packages, e.g. Appimage, that can be started in the Gitpod
workspace (using VNC since it's an Electron app).
The Gitpod config was taken from eclipse-theia/theia and slightly
adapted for this repo. I have added the generation of preview and
production packages for Linux. This provides an easy means of testing
and looking under the hood, e.g. for troubleshooting, in an
environment that should offer reproducibility.
~~For enhanced benefit we can consider having webmaster enable the
Gitpod integration for this repo. Then we'd have …
=> [WIP] add Gitpod config

Jenkinsfile
CI builds often timeout, especially when multiple builds are running. This PR increases the timeout from 3 to 5 hours.
=> Update Jenkinsfile timeout

Jenkinsfile
This PR aborts the entire job early if any of the build stages fail. Should save some CI compute as we don't allow concurrent builds.
Observe any failed build stages aborting the entire job
=> Abort builds early

README.md
* update download link and link to documentation
* adjust wording to match webpage
closes #23 
Check the readme
=> Update Readme of this repo #23

theia-blueprint-updater/src/electron-main/update/theia-updater-impl.ts
* record a download stat when user applies the update
Build locally with a version lower than the latest one available here: https://download.eclipse.org/theia/ (this will allow to update to the latest version available from the download server)
Check whether the a theia-blueprint-updater-<uuid> directory was created in your temp directory and whether it contains an empty update-file
=> Measure number of downloads #36

theia-blueprint-product/src/browser/theia-blueprint-contribution.tsx, theia-blueprint-product/src/browser/theia-blueprint-frontend-module.ts
Closes #83 
- Adds `Report Issue` and `Documentation` commands to the `Help` menu.
1. Click on the `Help` menu.
2. Confirm that `Report Issue` opens the [Issue: Bug Report](https://github.com/eclipse-theia/theia-blueprint/issues/new?assignees=&labels=&template=bug_report.md) page in a new browser window.
3. Confirm that `Documentation` opens the [Blueprint Documentation](https://theia-ide.org/docs/blueprint_documentation) page in a new browser window.
Signed-off-by: seantan22 <sean.a.tan@ericsson.com>
=> add 'report issue' and 'documentation' help menu items

README.md
Fixes the `readme` link for the `theia blueprint` logo.
View [rendered content](https://github.com/eclipse-theia/theia-blueprint/blob/d67255288c1139e91b8c8cc6f1947c026d4a181f/README.md).
=> readme: fix logo link

theia-extensions/theia-blueprint-updater/src/common/updater/theia-updater.ts, theia-extensions/theia-blueprint-updater/src/electron-browser/updater/theia-updater-frontend-contribution.ts, theia-extensions/theia-blueprint-updater/src/electron-main/update/theia-updater-impl.ts
* show that an error has happened
* the error we receive has no nice description of what went wrong so
just notify about error for now
* closes #45
Disconnect from the Internet and start an update (File -> Settings -> Check for Updates)
Error is reported as a message in bottom right corner
=> Improve error reporting on failed updates

theia-extensions/theia-blueprint-product/package.json, theia-extensions/theia-blueprint-product/src/browser/style/index.css, theia-extensions/theia-blueprint-product/src/browser/theia-blueprint-frontend-module.ts, theia-extensions/theia-blueprint-product/src/browser/theia-blueprint-getting-started-contribution.ts, theia-extensions/theia-blueprint-product/src/browser/theia-blueprint-getting-started-widget.tsx
* add actions on the right of the welcome page
* show welcome page on every start
closes #30
Build and check actions on welcome page
Open a workspace and restart. See if welcome page opens again
=> Should we add actions to the welcome page #30

Jenkinsfile, yarn.lock
A few small improvements that will, hopefully, help stabilize
the CI:
- added a few volumes so that some strategix folders are writable by the CI job
- added a retry mechanism for the `yarn` build call, so that it will automatically retry a couple of times in case of failure.
Check that CI has passed :) 
Existing PRs that have build issue might benefit from being re-based to include these improvements, once merged.
=> [Jenkins] Make CI more robust

theia-extensions/theia-blueprint-product/src/browser/theia-blueprint-about-dialog.tsx, theia-extensions/theia-blueprint-product/src/browser/theia-blueprint-getting-started-widget.tsx
Update release information on welcome page and about dialog from alpha to beta
Build and check welcome page and about dialog
=> Update release information from alpha to beta

yarn.lock
Signed-off-by: Atharva321 <atharvapatil19202@gmail.com>
Fixes: #127 
This PR updates the caniuse-lite browserslist dependency
=> Updating Browserslist Dependency caniuse-lite

Jenkinsfile
Second (hopefully final) follow-up, to fix Jenkins run when merging to master.
Fixed a typo in the RegExp that controls whether the full or streamline jenkins
run happens .
Cross fingers :)
=> [CI] follow-up: fix CI when merging take 2

Jenkinsfile
This time try checking "env.JOB_BASE_NAME" instead of
"env.GIT_BRANCH". Probably the later was noy yet set
when we need it.
Will need to merge to be sure.
=> [CI] follow-up: fix CI when merging take 3

theia-extensions/theia-blueprint-product/src/browser/branding-util.tsx, theia-extensions/theia-blueprint-product/src/browser/theia-blueprint-about-dialog.tsx, theia-extensions/theia-blueprint-product/src/browser/theia-blueprint-getting-started-widget.tsx
* update branding util to create links that open in the external browser
* update links to documentation
Closes #95 
Build theia blueprint and click on the links in the about-dialog and the welcome-page.
=> [About dialog] fix opening of external links #95

applications/electron/package.json, next/Jenkinsfile, next/NEXT_INTEGRATION_BUILD.md, package.json, scripts/update-theia-to-next.ts, theia-extensions/theia-blueprint-product/package.json, theia-extensions/theia-blueprint-updater/package.json, yarn.lock
This is the first part of solving issue #163
What is missing in this PR is executing the tests on all platforms (currently only executed for Windows). We only deal with compilation and building the packages for now. 
After this is merged the master branch has a script that may be used to update all theia versions to `next`. This may be executed running `yarn update:next` in the repository root.
We will set up an integration job that will build Blueprint against Theia@next so that we may identify breaking changes early. Currently this is tested here: https://ci.eclipse.org/theia/job/theia-next/job/jf%252Fnext/
* Check out the master branch containing all of the latest changes.
* Merge the next branch into the checked out branch. The next branch will only contain fixes that are required to …
=> Establish a nightly build against Theia latest main branch #163

README.md
Adds badges for the build status to read me
Badges can be checked on the source branch: https://github.com/eclipse-theia/theia-blueprint/tree/jf/badges
=> Add build status badges to Read Me

Jenkinsfile, next/Jenkinsfile
* switch to different ms visual studio version
* fixes #202
Jenkins windows build should work again
=> electron-rebuild fails on Eclipse jenkins on the Windows Node #202

yarn.lock
Due to https://github.com/eclipse-theia/theia-blueprint/pull/220, we need to update the `yarn.lock` so there is no diff when building the application locally.
- confirm there is no diff when building
- confirm that CI passes successfully
=> repo: update `yarn.lock`

applications/electron/resources/preload.html
This patch fixes the flickering of the preload. I noticed this minor UI glitch while copy-pasting this great blueprint example to another downstream app.
Before:
After:
Build the IDE and start it.
=> Fixed the preload flickering.

.github/workflows/build.yml
The pull-request updates the deprecated runners in favor of `latest` for each operating system, and also updates actions to clean up warning annotations.
Confirm that CI passes, and warning annotations are cleaned up (ex: [old run](https://github.com/eclipse-theia/theia-blueprint/actions/runs/3566021262)).
=> ci: update runners and actions

.vscode/launch.json, applications/electron/package.json, theia-extensions/theia-blueprint-launcher/README.md, theia-extensions/theia-blueprint-launcher/package.json, theia-extensions/theia-blueprint-launcher/src/browser/create-launcher-contribution.ts, theia-extensions/theia-blueprint-launcher/src/browser/create-launcher-frontend-module.ts, theia-extensions/theia-blueprint-launcher/src/browser/launcher-service.ts, theia-extensions/theia-blueprint-launcher/src/node/launcher-backend-module.ts, theia-extensions/theia-blueprint-launcher/src/node/launcher-endpoint.ts, theia-extensions/theia-blueprint-launcher/tsconfig.json, yarn.lock
For AppImage applications, offer the option to create a script that allows to start blueprint from the command line by calling the 'theia' command.
On startup. the user is asked if they want to install the shell command. The preference is saved in `$HOME/.theia-blueprint/globalStorage/blueprint-launcher/paths.json`. 
The `paths.json` file contains a list of entries with a `source` and a `target`:
* `source` represents the location in which the shell script that launches the application is created,
* `target` represents the location of the AppImage that will be launched by the `source` script. 
If the user does not wish to create the shell command, the `target` will be empty.
1. Build and package the application
2. Start Blueprint from the AppImage file
3. A dialog should pop-up on …
=> Open current folder in Theia from terminal

applications/browser/package.json, applications/electron/package.json
Remove theia/scm-extra package from browser blueprint, per advice in https://github.com/eclipse-theia/theia/issues/10786#issuecomment-1049971777
Verify that the (broken) History option is gone from the View menu, but no other functionality is impacted.
=> Remove scm-extra

applications/electron/package.json
Fixes electron app parameters to never stop any back end connection contexts.
I can't really...need a build.
=> Fix reconnect parameters

.github/workflows/build.yml, Jenkinsfile
In order to fix https://github.com/eclipse-theia/theia-blueprint/pull/340 we need to update the node version on our CI. 
Check the result on the builds below. 
=> Update CI node version to ~20

.github/workflows/license-check-workflow.yml, .gitignore, configs/license-check-config.json, package.json, yarn.lock
* adds scripts and workflow for license checks
* enable automatic review
Check workflow on this PR
Run script locally using `yarn license:check`
=> Integrate License Check

PUBLISHING.md
=> Describe preview release process

README.md
=> Add "experimental" to Docker build and link it

theia-extensions/launcher/src/node/desktopfile-endpoint.ts
Change StartupWMClass to Theia IDE so it can be added to favorites. Change the name of the entries to Theia IDE for consistency.
=> Fix desktop entries

PUBLISHING.md, README.md, applications/browser/package.json, applications/electron/package.json, package.json, theia-extensions/launcher/package.json, theia-extensions/product/package.json, theia-extensions/product/src/browser/branding-util.tsx, theia-extensions/product/src/browser/theia-ide-contribution.tsx, theia-extensions/updater/package.json
* update links and documentation
closes #339
-
=> Rename the repository from Theia Blueprint to Theia IDE #339

README.md
=> Fixed license in Readme

applications/electron/electron-builder.yml, yarn.lock
`yarn upgrade`
Build and verify everything is still working
=> Run yarn upgrade

applications/browser/package.json, applications/electron/package.json, lerna.json, package.json, theia-extensions/launcher/package.json, theia-extensions/product/package.json, theia-extensions/updater/package.json, yarn.lock
Add huggingface support
Bump Theia IDE version to 1.56.1
=> Add @theia/ai-huggingface

applications/browser/package.json, applications/electron/package.json, lerna.json, package.json, theia-extensions/launcher/package.json, theia-extensions/product/package.json, theia-extensions/updater/package.json, yarn.lock
Increase version to 1.56.2
See https://github.com/eclipse-theia/theia/issues/14586
=> Fix perfect-scrollbar to 1.5.5

.vscode/settings.json, PUBLISHING.md, README.md
=> Update publishing guide and format md files

PUBLISHING.md
Changes include:
- Properly reordered the steps
- Added release commit tagging section
- Added Snap Update Section
- Clean up style of the guide and unify it
=> Update Publishing guide

Jenkinsfile
Previous failed with:
```
WorkflowScript: 12: 
(toStashDist - mac) is a binary expression, but it should be a variable expression at line: 12 column: 17. File: WorkflowScript @ line 12, column 17.
toStashDist-mac = "${distFolder}/mac-x64/**"
^
1 error
at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:309)
at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:981)
at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:626)
at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:602)
at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:579)
at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:323)
at …
```
=> Fix variable name

Jenkinsfile
=> Split Mac uploads as they seem to hit the quota limit

.github/workflows/build.yml
Whenever a new master commit, scheduled or triggered build run is executed, we now upload the packaged app to the artifacts. We already did that for the mac build, because we need it for the publishing, but now we do it for the other systems as well. But only on non PRs to not increase the PR build time.
=> Upload packaged app on non PR runs

.github/workflows/build.yml
windows-2019 runner will be removed soon -> update to windows-2022
See https://github.com/actions/runner-images/issues/12045
=> windows-2019 runner will be removed soon -> update to windows-2022

Dockerfile
=> Update dockerfile node version

Jenkinsfile
=> Use node 22 for mac as well

Jenkinsfile
=> Debug msvs environment variables

releng/preview/Jenkinsfile.sign, releng/preview/Jenkinsfile.upload
After merging we need to point https://ci.eclipse.org/theia/job/theia-ide-upload/ and https://ci.eclipse.org/theia/job/theia-ide-sign-notarize/ to the master branch.
=> Improve CI

releng/preview/Jenkinsfile.build, releng/preview/Jenkinsfile.sign, releng/preview/Jenkinsfile.upload
- add option for maximum survivability for pipelines
- ensure target folder is cleaned inbetween jobs
- simplify dry-run
- fix notarizeInstaller polling for signing
- update resource memory limits and requests for upload
check latest dry-run result upload here: https://ci.eclipse.org/theia/job/theia-ide-upload/20/
(this run is based on this PR branch)
=> chore: update Jenkins files for build, sign and upload

yarn.lock
Upgrade dependencies after release v1.64.100
=> Yarn upgrade after release v1.64.100
